// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhnymiterxovztkngyxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhobnltaXRlcnhvdnp0a25neXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDAwMjUsImV4cCI6MjA1ODIxNjAyNX0.MRd0QXBYQWybrdPukk4QCUfQdzdGXSUte1sQbHtib08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);